model: "gpt-4"
csv_file: "presidents_info_gpt4.csv"
questions:
  - key: "Term"
    question: "What was {president}'s term as president? Answer only with a date range. Ex. YYYY-MM-DD to YYYY-MM-DD"
  - key: "Date of Birth"
    question: "What was the date of birth for {president}? Answer in the format: YYYY-MM-DD"
  - key: "Age at Inauguration"
    question: "What was {president}'s age at inauguration? Answer with a single number: ex. 52"
  - key: "Age at exit from office"
    question: "What was {president}'s age at exit from office? Answer with a single number: ex. 63"
  - key: "Date of Death"
    question: "What was {president}'s date of death? Answer in the format: YYYY-MM-DD."
  - key: "Age at Death"
    question: "What was {president}'s age at death? Answer with a single number: ex. 82"
  - key: "Prior Gov Experience"
    question: "What was {president}'s prior government role before becoming president? Please provide your answer concisely in a few words: ex. Secretary of the Treasury."
  - key: "Prior Political Experience"
    question: "What was {president}'s other political role before becoming president? Please provide your answer in few words: ex. Governor of California."
  - key: "Military Service"
    question: "Did {president} serve in the military prior to becoming president? Yes or No."
  - key: "Religion"
    question: "What was {president}'s religion? Please provide your answer in 1-2 words"
policy_questions:
  - key_base: "Major Domestic Policy Issue"
    question: "What were two major domestic challenges faced by {president}? Separate responses by a semicolon (;). Please provide your answer in 1-2 sentences."
  - key_base: "Major Foreign Policy Issue"
    question: "What were two major foreign policy challenges faced by {president}? Separate responses by a semicolon (;). Please provide your answer in 1-2 sentences."